# Action Requires
# 1. Setup the AZURE_CREDENTIALS secrets in your GitHub Repository
# 2. Setup the REGISTRY_USERNAME secrets in your GitHub Repository
# 3. Setup the REGISTRY_PASSWORD secrets in your GitHub Repository
# 4. Replace REGISTRY, NAMESPACE, IMAGE, TAG in the following template with proper values
# 5. Add this yaml file to your project's .github/workflows/
# 6. Push your local project to your GitHub Repository

name: Docker Hub Container

on: workflow_dispatch

env: 
  REGISTRY: valetregistry.azurecr.io
  NAMESPACE: rogerprz
  IMAGE: azurefunctionsimage
  TAG: v1.0.1
  WORK_DIR: LocalFunctionsProject
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CONTAINER_CREDS }}
    - name: 'Run Azure Functions Container Action'
      uses: Azure/functions-container-action@v1
      id: fa
      with:
        app-name: valet-container-app
        image: ${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.TAG }}

    - name: Azure logout
      run: |
        az logout
# For more information on GitHub Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actions
